### PR TITLE
make installation code more copy-paste friendly

### PR DESCRIPTION
**Pull request by benmarwick**
I think most readers will know it's R code without needing the prompt.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
That comes up every now and then (here, on SO, other places, ...) as the new _`vi` versus `emacs`_ issue, and I am standing firm here.  I adopted the _explicit_ prompt _on purposes_ following the same argument that imposes the prompt for code samples in one of the journals -- I believe it was JSS.

So, no, sorry.  A feature to me, not a bug.  You'll need to copy part of the line.

**Comment by benmarwick** [comment]
I see, I wasn't aware is is such a divisive issue. I see that the [JSS author guidelines](https://www.jstatsoft.org/about/submissions) do prefer the prompt style you use, but don't give any justification (I'm curious to know, maybe I should be using that prompt too!). But that doesn't matter here, your repo, your choice, no need to explain.

**Comment by eddelbuettel** [comment]
I didn't do it before it I first submited to JSS; they admittedly do not have color at their disposal.  But they, like GitHub, deal with several languages so it is defensible there. I think Achim even recommended that choice for the console prompt, and that is what I do:

```r
## AER page vii                                                                                                                                                                                                     
options(prompt="R> ") 
```

and that reminds me -- it is on page vii of his book _Applied Econometrics with R_.

I find the issue annoying.  Some folks (incl Yihui) are extremely opinionated on this; there were (apparently) occasional StackOverflow editing wars on it too -- it is all kinda silly.   If you in doubt just always have drat installed and the ghrr repo set :)

But thanks for caring enough, and following tint.  I take this as a tacit endorsement of getting tint into tufte?

**Comment by benmarwick** [comment]
Yes, thanks for that background, I hadn't looked into Achim's book until you mentioned it just now, thanks for the tip. I've posted an issue about including tint in rstudio/tufte. It would be very handy to have this nice sans-serif tufte template included with the RStudio products.

If I understand correctly, the main advantage of drat over `devtools::install_github` (for someone like me who is mainly a user of packages, rather than an author) is that packages installed with drat will be updated when `update.packages` is run (if there is an update available). But packages installed with `devtools::install_github` are not included in the `update.packages` process, is that right?

**Comment by eddelbuettel** [comment]
My main starting point is that `install_github()` is the worst possible option.  You get _users_ to pick random install snapshot (you may just be in the middle of committing a chain of updates), you don't really get dependencies resolved, and you barely have identification as a sha1 doesn't really count.

My view is that _releases_ matter, are understood and work.  And drat allows anybody to create a repo -- just like CRAN -- which will be supported by `install.packages()`, `update.packages()`, and all the rest.  Why break what works?

End of sermon.

**Comment by benmarwick** [comment]
Thanks for that further explanation, that's very helpful. Looking again at the [pkg overview](http://dirk.eddelbuettel.com/code/drat.html) I see that you do mention the emphasis on releases. 

I suppose I was expecting that important detail about the motivation for drat to appear earlier, in the 'Background' section. But I've got it now, thanks again!

**Comment by eddelbuettel** [comment]
I must have written more vignettes and documentation _about_ drat than code _inside_ it, and still find it difficult to explain.   Oh well.

If you have a good idea about where to state that more clearly or eloquently, I'd be all ears.

**Comment by benmarwick** [comment]
For the common-or-garden R user (not sure if that's your target audience with drat, but that's where I'm coming from), I reckon something like this would help them see how drat could be useful. Perhaps the README.md 'Background' section could start with a few lines like this, re-using some of your explanation above:  

>The motivation for drat is to give package authors more control over how they make their packages available to users. It does this by enabling package authors to make releases on a GitHub repository (or any server). drat allows anyone to create their own package repository -- just like CRAN. There are two key advantages of using drat over other methods of installing packages from GitHub (e.g. `devtools::install_github`). First is that a package installed from a drat repository will be supported by `install.packages()` and `update.packages()`, so the user has easy methods for keeping updated. A second advantage of using drat is that the package author can control what other people get when they download your package from GitHub. With other methods, users typically download a random install snapshot, which might have unexpected consequences for them. 

It could also go at the top of the FAQ file. But looking at your monthly downloads, it seems that a lot of people have already got a good understanding of drat!

**Comment by eddelbuettel** [comment]
Thank you.  Those are the key points I think I am making, but maybe in too scattered a fashion in too many place.  Will see where to place this.

Your comment re `R> ` prompts also gave me pause.  On GitHub, it just does not render well -- so for [anytime](github.com/eddelbuettel/anytime/) I actually _did_ edit it out.  It reads better now.  So thanks!

**Comment by eddelbuettel** [comment]
@benmarwick I just added what you wrote near the very top of the FAQ.

**Pull request closed without merging**
